name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - run: npm ci

      - run: npm run test-ci

      - run: npm run bench
